from __future__ import annotations

import json
import stat
import sys
from pathlib import Path

from ase.io import read, write

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ROOT, active_model_ids, load_config, load_metadata, load_model


# Exact aliases verified against the official CP2K BASIS_MOLOPT and
# GTH_POTENTIALS files on 2026-07-17.  The q values must match between each
# basis and pseudopotential.
SMOKE_BASIS = {
    "Cu": ("DZVP-MOLOPT-SR-GTH-q11", "GTH-PBE-q11", 11),
    "Cd": ("DZVP-MOLOPT-SR-GTH-q12", "GTH-PBE-q12", 12),
    "Te": ("DZVP-MOLOPT-SR-GTH-q6", "GTH-PBE-q6", 6),
}

SMOKE_TASKS = (
    {"id": "01_cdte_bulk_sp", "source": "cdte_bulk", "run_type": "ENERGY_FORCE", "periodic": "XYZ"},
    {"id": "02_cu2te_bulk_sp", "source": "cu2te_bulk", "run_type": "ENERGY_FORCE", "periodic": "XYZ"},
    {"id": "03_b0_slab_sp", "source": "B0", "run_type": "ENERGY_FORCE", "periodic": "XY"},
    {"id": "04_h1_interface_sp", "source": "H1", "run_type": "ENERGY_FORCE", "periodic": "XY"},
    {"id": "05_h1_short_geo_opt", "source": "H1", "run_type": "GEO_OPT", "periodic": "XY"},
)


def fmt_vector(vector) -> str:
    return " ".join(f"{float(value):16.9f}" for value in vector)


def render_input(
    atoms,
    project: str,
    run_type: str,
    periodic: str,
    config: dict,
    fixed_indices_1based: list[int] | None = None,
) -> str:
    cp = config["cp2k"]
    coordinates = "\n".join(
        f"      {symbol:2s} {position[0]:16.9f} {position[1]:16.9f} {position[2]:16.9f}"
        for symbol, position in zip(atoms.get_chemical_symbols(), atoms.positions)
    )
    kinds = []
    for element in ("Cd", "Te", "Cu"):
        if element not in atoms.get_chemical_symbols():
            continue
        basis, potential, q = SMOKE_BASIS[element]
        kinds.append(
            f"""    &KIND {element}
      ELEMENT {element}
      BASIS_SET {basis}
      POTENTIAL {potential}
      # Matching GTH valence-electron setting: q{q}
    &END KIND"""
        )
    poisson_solver = "      PSOLVER ANALYTIC\n" if periodic == "XY" else ""
    added_mos = cp["added_mos"] if len(atoms) > 20 else min(cp["added_mos"], 20)
    motion = ""
    if run_type == "GEO_OPT":
        if not fixed_indices_1based:
            raise ValueError("GEO_OPT input requires explicit fixed substrate atom indices")
        fixed = " ".join(str(index) for index in fixed_indices_1based)
        motion = f"""
&MOTION
  &CONSTRAINT
    &FIXED_ATOMS
      LIST {fixed}
      COMPONENTS_TO_FIX XYZ
    &END FIXED_ATOMS
  &END CONSTRAINT
  &GEO_OPT
    OPTIMIZER BFGS
    MAX_ITER {cp['geo_opt_test_max_iter']}
    MAX_FORCE 4.5E-4
    RMS_FORCE 3.0E-4
    MAX_DR 3.0E-3
    RMS_DR 1.5E-3
  &END GEO_OPT
  &PRINT
    &TRAJECTORY
      FORMAT XYZ
    &END TRAJECTORY
    &FORCES ON
    &END FORCES
    &RESTART
      BACKUP_COPIES 1
    &END RESTART
  &END PRINT
&END MOTION
"""
    return f"""# Generated by scripts/generate_cp2k_inputs.py
# SMOKE TEST ONLY: PBE/DZVP, cutoff, Gamma point and model size are not converged.
&GLOBAL
  PROJECT {project}
  RUN_TYPE {run_type}
  PRINT_LEVEL MEDIUM
&END GLOBAL

&FORCE_EVAL
  METHOD QUICKSTEP
  &DFT
    BASIS_SET_FILE_NAME {cp['basis_file']}
    POTENTIAL_FILE_NAME {cp['potential_file']}
    CHARGE 0
    MULTIPLICITY 1
    &QS
      METHOD GPW
      EPS_DEFAULT 1.0E-12
    &END QS
    &POISSON
      PERIODIC {periodic}
{poisson_solver}    &END POISSON
    &MGRID
      CUTOFF {cp['cutoff_ry']}
      REL_CUTOFF {cp['rel_cutoff_ry']}
    &END MGRID
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF {cp['eps_scf']}
      MAX_SCF {cp['max_scf']}
      ADDED_MOS {added_mos}
      &DIAGONALIZATION
        ALGORITHM STANDARD
      &END DIAGONALIZATION
      &SMEAR ON
        METHOD FERMI_DIRAC
        ELECTRONIC_TEMPERATURE [K] {cp['electronic_temperature_k']}
      &END SMEAR
      &MIXING ON
        METHOD BROYDEN_MIXING
        ALPHA 0.20
        NBROYDEN 8
      &END MIXING
      # Explicit OFF is required: at MEDIUM print level CP2K otherwise writes
      # a k-point restart tens of MB large even for a six-atom cell.
      &PRINT
        &RESTART OFF
        &END RESTART
      &END PRINT
    &END SCF
    &XC
      &XC_FUNCTIONAL PBE
      &END XC_FUNCTIONAL
    &END XC
    &KPOINTS
      SCHEME GAMMA
    &END KPOINTS
  &END DFT
  &SUBSYS
    &CELL
      A {fmt_vector(atoms.cell[0])}
      B {fmt_vector(atoms.cell[1])}
      C {fmt_vector(atoms.cell[2])}
      PERIODIC {periodic}
    &END CELL
    &COORD
{coordinates}
    &END COORD
{chr(10).join(kinds)}
  &END SUBSYS
  &PRINT
    &FORCES ON
    &END FORCES
  &END PRINT
&END FORCE_EVAL
{motion}"""


def write_model_scripts(model_dir: Path, model_id: str, config: dict) -> None:
    threads = config["cp2k"]["local_max_threads"]
    shell_text = f"""#!/usr/bin/env bash
set -euo pipefail
input=${{1:-single_point.inp}}
output=${{input%.inp}}.out
cmd=${{CP2K_CMD:-}}
if [[ -z "$cmd" ]]; then
  for candidate in cp2k.psmp cp2k.popt cp2k; do
    if command -v "$candidate" >/dev/null 2>&1; then cmd=$candidate; break; fi
  done
fi
if [[ -z "$cmd" ]]; then echo "ERROR: CP2K not found. Set CP2K_CMD." >&2; exit 127; fi
export OMP_NUM_THREADS=${{OMP_NUM_THREADS:-{threads}}}
"$cmd" -i "$input" -o "$output"
"${{PYTHON:-python}}" ../../scripts/parse_cp2k_output.py "$output" --input "$input"
"""
    powershell_text = f"""param([string]$InputFile = 'single_point.inp')
$ErrorActionPreference = 'Stop'
$cmd = $env:CP2K_CMD
if (-not $cmd) {{ foreach ($candidate in @('cp2k.psmp','cp2k.popt','cp2k')) {{ if (Get-Command $candidate -ErrorAction SilentlyContinue) {{ $cmd=$candidate; break }} }} }}
if (-not $cmd) {{ throw 'CP2K not found. Set CP2K_CMD.' }}
if (-not $env:OMP_NUM_THREADS) {{ $env:OMP_NUM_THREADS='{threads}' }}
$OutputFile = [IO.Path]::ChangeExtension($InputFile, '.out')
& $cmd -i $InputFile -o $OutputFile
& $env:PYTHON ../../scripts/parse_cp2k_output.py $OutputFile --input $InputFile
"""
    cpus, wall = config["cp2k"]["slurm_cpus"], config["cp2k"]["slurm_time"]
    slurm_text = f"""#!/usr/bin/env bash
#SBATCH --job-name={model_id.lower()}_cute_smoke
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --time={wall}
#SBATCH --output=slurm-%j.out
# Add site-specific account/partition/module settings before use.
set -euo pipefail
export OMP_NUM_THREADS=${{SLURM_CPUS_PER_TASK:-{cpus}}}
CP2K_CMD=${{CP2K_CMD:-cp2k.psmp}}
srun "$CP2K_CMD" -i single_point.inp -o single_point.out
"""
    for filename, content in (
        ("run_local.sh", shell_text),
        ("run_local.ps1", powershell_text),
        ("job.slurm", slurm_text),
    ):
        path = model_dir / filename
        path.write_text(content, encoding="utf-8", newline="\n")
        if filename.endswith((".sh", ".slurm")):
            path.chmod(path.stat().st_mode | stat.S_IEXEC)


def smoke_source(task: dict):
    if task["source"] == "cdte_bulk":
        atoms = read(ROOT / "structures" / "bulk" / "CdTe_AFLOW_mp406.cif")
        atoms.pbc = (True, True, True)
        return atoms, []
    if task["source"] == "cu2te_bulk":
        atoms = read(ROOT / "structures" / "bulk" / "Cu2Te_AFLOW_icsd655706.cif")
        atoms.pbc = (True, True, True)
        return atoms, []
    atoms = load_model(task["source"])
    fixed = load_metadata(task["source"])["fixed_atom_indices_cp2k_1based"]
    return atoms, fixed


def write_smoke_tests(config: dict) -> None:
    smoke_root = ROOT / "smoke_tests"
    smoke_root.mkdir(exist_ok=True)
    manifest = []
    for task in SMOKE_TASKS:
        atoms, fixed = smoke_source(task)
        task_dir = smoke_root / task["id"]
        task_dir.mkdir(parents=True, exist_ok=True)
        project = task["id"].replace("-", "_")
        input_text = render_input(
            atoms,
            project,
            task["run_type"],
            task["periodic"],
            config,
            fixed if task["run_type"] == "GEO_OPT" else None,
        )
        (task_dir / "input.inp").write_text(input_text, encoding="utf-8", newline="\n")
        write(task_dir / "structure.cif", atoms, format="cif")
        write(task_dir / "structure.xyz", atoms, format="xyz")
        manifest.append(
            {
                **task,
                "atom_count": len(atoms),
                "input_file": str((task_dir / "input.inp").relative_to(ROOT)).replace("\\", "/"),
                "output_file": str((task_dir / "output.out").relative_to(ROOT)).replace("\\", "/"),
            }
        )
    (smoke_root / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    slurm = """#!/usr/bin/env bash
#SBATCH --job-name=cdte_cu2te_smoke
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --output=smoke-tests-%j.out
# Add site-specific account, partition and module commands before submitting.
set -euo pipefail
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK:-8}
python scripts/run_smoke_tests.py --mode native --cp2k-command "${CP2K_CMD:-cp2k.psmp}"
"""
    slurm_path = smoke_root / "run_smoke_tests.slurm"
    slurm_path.write_text(slurm, encoding="utf-8", newline="\n")
    slurm_path.chmod(slurm_path.stat().st_mode | stat.S_IEXEC)


def main() -> int:
    config = load_config()
    for model_id in active_model_ids():
        model_dir = ROOT / "models" / model_id
        atoms = load_model(model_id)
        meta = load_metadata(model_id)
        (model_dir / "single_point.inp").write_text(
            render_input(atoms, f"{model_id.lower()}_sp", "ENERGY_FORCE", "XY", config),
            encoding="utf-8",
            newline="\n",
        )
        if model_id == "H1":
            (model_dir / "test_geo_opt.inp").write_text(
                render_input(
                    atoms,
                    "h1_test_opt",
                    "GEO_OPT",
                    "XY",
                    config,
                    meta["fixed_atom_indices_cp2k_1based"],
                ),
                encoding="utf-8",
                newline="\n",
            )
        write_model_scripts(model_dir, model_id, config)
        print(f"generated CP2K smoke-profile inputs for {model_id}")
    write_smoke_tests(config)
    print("generated ordered smoke-test ladder")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
