from __future__ import annotations

import json
import sys
from pathlib import Path

from ase.io import read, write

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ROOT, load_config
from generate_cp2k_inputs import SMOKE_BASIS, fmt_vector


RESEARCH_TASKS = (
    ("cu2te_bulk", "bulk", "structures/bulk/Cu2Te_AFLOW_icsd655706.cif", "XYZ"),
    ("B0", "active", "models/B0/structure.extxyz", "XY"),
    ("C50", "coverage", "coverage_models/C50/structure.extxyz", "XY"),
    ("C100", "coverage", "coverage_models/C100/structure.extxyz", "XY"),
    ("H1", "active", "models/H1/structure.extxyz", "XY"),
    ("H2", "active", "models/H2/structure.extxyz", "XY"),
)


def _index_expression(indices: list[int]) -> str:
    if not indices:
        raise ValueError("LDOS group cannot be empty")
    values = sorted(set(indices))
    chunks: list[str] = []
    start = previous = values[0]
    for value in values[1:]:
        if value == previous + 1:
            previous = value
            continue
        chunks.append(str(start) if start == previous else f"{start}..{previous}")
        start = previous = value
    chunks.append(str(start) if start == previous else f"{start}..{previous}")
    return " ".join(chunks)


def region_groups(atoms, source_kind: str) -> list[dict]:
    symbols = atoms.get_chemical_symbols()
    if source_kind == "bulk":
        return [
            {"label": "Cu_bulk", "indices_1based": [i + 1 for i, s in enumerate(symbols) if s == "Cu"]},
            {"label": "Te_bulk", "indices_1based": [i + 1 for i, s in enumerate(symbols) if s == "Te"]},
        ]
    if "component" not in atoms.arrays:
        raise ValueError("slab structure lacks the component classification array")
    components = [str(value) for value in atoms.arrays["component"]]
    groups = [
        {"label": "CdTe_substrate", "indices_1based": [i + 1 for i, value in enumerate(components) if value == "cdte_substrate"]}
    ]
    film = [i + 1 for i, value in enumerate(components) if value == "cu2te_film"]
    if film:
        groups.append({"label": "Cu2Te_film", "indices_1based": film})
    return groups


def _kpoints_block(mesh: list[int] | str) -> str:
    if mesh == "implicit":
        return "    # Implicit Gamma: no KPOINTS section, preserving CP2K 2024.3 PDOS/LDOS support."
    return f"""    &KPOINTS
      SCHEME MONKHORST-PACK {mesh[0]} {mesh[1]} {mesh[2]}
    &END KPOINTS"""


def render_research_lite(atoms, project: str, periodic: str, groups: list[dict], config: dict, kpoints: list[int] | str, enable_pdos: bool = True) -> str:
    cp_root = config["cp2k"]
    cp = cp_root["profiles"]["research_lite"]
    coordinates = "\n".join(
        f"      {symbol:2s} {position[0]:16.9f} {position[1]:16.9f} {position[2]:16.9f}"
        for symbol, position in zip(atoms.get_chemical_symbols(), atoms.positions)
    )
    kinds = []
    for element in ("Cd", "Te", "Cu"):
        if element not in atoms.get_chemical_symbols():
            continue
        basis, potential, q = SMOKE_BASIS[element]
        kinds.append(
            f"""    &KIND {element}
      ELEMENT {element}
      BASIS_SET {basis}
      POTENTIAL {potential}
      # Matching GTH valence setting q{q}
    &END KIND"""
        )
    ldos = []
    for number, group in enumerate(groups, start=1):
        ldos.append(
            f"""      # LDOS group {number}: {group['label']}
      &LDOS
        LIST {_index_expression(group['indices_1based'])}
        COMPONENTS
      &END LDOS"""
        )
    poisson_solver = "      PSOLVER ANALYTIC\n" if periodic == "XY" else ""
    stride = " ".join(str(value) for value in cp["potential_cube_stride"])
    restart_section = """      &PRINT
        &RESTART ON
          BACKUP_COPIES 1
        &END RESTART
      &END PRINT""" if cp["save_restart_wfn"] else """      &PRINT
        &RESTART OFF
        &END RESTART
      &END PRINT"""
    pdos_section = f"""      &PDOS ON
        NLUMO {cp['pdos_nlumo']}
        COMPONENTS
{chr(10).join(ldos)}
      &END PDOS""" if enable_pdos else """      # PDOS/LDOS intentionally omitted for this explicit k-point check:
      # CP2K 2024.3 reports that projected DOS is not implemented for KPOINTS."""
    return f"""# Generated by scripts/generate_research_lite_inputs.py
# PROFILE research_lite: trend-oriented starting point, not publication-converged.
# The polar CdTe(111) slabs may only support relative trend checks after further convergence work.
&GLOBAL
  PROJECT {project}
  RUN_TYPE {cp['run_type']}
  PRINT_LEVEL {cp['print_level']}
&END GLOBAL

&FORCE_EVAL
  METHOD QUICKSTEP
  &DFT
    BASIS_SET_FILE_NAME {cp_root['basis_file']}
    POTENTIAL_FILE_NAME {cp_root['potential_file']}
    CHARGE 0
    MULTIPLICITY 1
    &QS
      METHOD GPW
      EPS_DEFAULT {cp['eps_default']}
    &END QS
    &POISSON
      PERIODIC {periodic}
{poisson_solver}    &END POISSON
    &MGRID
      CUTOFF {cp['cutoff_ry']}
      REL_CUTOFF {cp['rel_cutoff_ry']}
    &END MGRID
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF {cp['eps_scf']}
      MAX_SCF {cp['max_scf']}
      ADDED_MOS {cp['added_mos']}
      &{cp['scf_method']}
        ALGORITHM STANDARD
      &END {cp['scf_method']}
      &SMEAR ON
        METHOD FERMI_DIRAC
        ELECTRONIC_TEMPERATURE [K] {cp['electronic_temperature_k']}
      &END SMEAR
      &MIXING ON
        METHOD {cp['mixing_method']}
        ALPHA {cp['mixing_alpha']}
        NBROYDEN {cp['mixing_nbroyden']}
      &END MIXING
{restart_section}
    &END SCF
    &XC
      &XC_FUNCTIONAL {cp['xc_functional']}
      &END XC_FUNCTIONAL
    &END XC
{_kpoints_block(kpoints)}
    &PRINT
      &DOS ON
        DELTA_E {cp['dos_delta_e_hartree']}
        FILENAME =total_dos.dat
      &END DOS
{pdos_section}
      # CP2K's V_HARTREE_CUBE contains the electron+ion electrostatic potential
      # with the opposite sign to the conventional physical potential.
      &V_HARTREE_CUBE ON
        FILENAME =hartree_potential.cube
        STRIDE {stride}
      &END V_HARTREE_CUBE
      &E_DENSITY_CUBE ON
        FILENAME =electron_density.cube
        STRIDE {stride}
      &END E_DENSITY_CUBE
    &END PRINT
  &END DFT
  &SUBSYS
    &CELL
      A {fmt_vector(atoms.cell[0])}
      B {fmt_vector(atoms.cell[1])}
      C {fmt_vector(atoms.cell[2])}
      PERIODIC {periodic}
    &END CELL
    &COORD
{coordinates}
    &END COORD
{chr(10).join(kinds)}
  &END SUBSYS
&END FORCE_EVAL
"""


def main() -> int:
    config = load_config()
    cp = config["cp2k"]["profiles"]["research_lite"]
    root = ROOT / "research_lite" / "inputs"
    manifest = []
    for calculation_id, source_kind, source_path, periodic in RESEARCH_TASKS:
        atoms = read(ROOT / source_path)
        atoms.pbc = tuple(axis in periodic for axis in "XYZ")
        groups = region_groups(atoms, source_kind)
        task_dir = root / calculation_id
        task_dir.mkdir(parents=True, exist_ok=True)
        gamma_input = task_dir / "input_gamma.inp"
        gamma_input.write_text(
            render_research_lite(atoms, f"rl_{calculation_id.lower()}_gamma", periodic, groups, config, cp["gamma_kpoints"], enable_pdos=True),
            encoding="utf-8",
            newline="\n",
        )
        check_input = task_dir / "input_k221_check.inp"
        check_input.write_text(
            render_research_lite(atoms, f"rl_{calculation_id.lower()}_k221", periodic, groups, config, cp["optional_kpoint_check"], enable_pdos=False),
            encoding="utf-8",
            newline="\n",
        )
        write(task_dir / "structure.cif", atoms, format="cif")
        write(task_dir / "structure.xyz", atoms, format="xyz")
        prior_run = ROOT / "research_lite" / "runs" / calculation_id / "output.parsed.json"
        actually_run = False
        if prior_run.is_file():
            actually_run = bool(json.loads(prior_run.read_text(encoding="utf-8")).get("actually_run"))
        manifest.append(
            {
                "calculation_id": calculation_id,
                "source_kind": source_kind,
                "source_structure": source_path,
                "periodic": periodic,
                "atom_count": len(atoms),
                "gamma_input": str(gamma_input.relative_to(ROOT)).replace("\\", "/"),
                "optional_k221_input": str(check_input.relative_to(ROOT)).replace("\\", "/"),
                "gamma_capabilities": ["Fermi energy", "DOS", "PDOS/LDOS", "Hartree potential", "electron density"],
                "optional_k221_capabilities": ["Fermi energy", "DOS", "Hartree potential", "electron density"],
                "optional_k221_limitation": "CP2K 2024.3 does not implement PDOS/LDOS when a KPOINTS section is active",
                "ldos_groups": groups,
                "actually_run": actually_run,
                "run_directory": f"research_lite/runs/{calculation_id}" if actually_run else None,
            }
        )
        print(f"{calculation_id}: generated Gamma and optional 2x2x1 research_lite inputs")
    manifest_path = ROOT / "research_lite" / "manifest.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
