from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

from common import ROOT


PACKAGE = ROOT / "server_scnet_2024_1"
SOURCE_INPUTS = ROOT / "research_lite" / "inputs"

TASKS = {
    "cu2te_bulk_gamma": {
        "source": "cu2te_bulk/input_k222_check.inp",
        "input_dir": "cu2te_bulk",
        "input_name": "input_gamma.inp",
        "project": "scnet_cu2te_bulk_gamma",
        "kpoint_mesh": "Gamma",
        "expected_electronic_outputs": False,
        "formula_units": 2,
        "substrate_area_angstrom2": None,
    },
    "cu2te_bulk_k222": {
        "source": "cu2te_bulk/input_k222_check.inp",
        "input_dir": "cu2te_bulk",
        "input_name": "input_k222.inp",
        "project": "scnet_cu2te_bulk_k222",
        "kpoint_mesh": "2x2x2",
        "expected_electronic_outputs": False,
        "formula_units": 2,
        "substrate_area_angstrom2": None,
    },
    "cu2te_bulk_k333": {
        "source": "cu2te_bulk/input_k222_check.inp",
        "input_dir": "cu2te_bulk",
        "input_name": "input_k333.inp",
        "project": "scnet_cu2te_bulk_k333",
        "kpoint_mesh": "3x3x3",
        "expected_electronic_outputs": False,
        "formula_units": 2,
        "substrate_area_angstrom2": None,
    },
    "cu2te_bulk_k444": {
        "source": "cu2te_bulk/input_k222_check.inp",
        "input_dir": "cu2te_bulk",
        "input_name": "input_k444.inp",
        "project": "scnet_cu2te_bulk_k444",
        "kpoint_mesh": "4x4x4",
        "expected_electronic_outputs": False,
        "formula_units": 2,
        "substrate_area_angstrom2": None,
    },
    "B0": {
        "source": "B0/input_gamma.inp",
        "input_dir": "B0",
        "input_name": "input.inp",
        "project": "scnet_b0",
        "kpoint_mesh": "Gamma",
        "expected_electronic_outputs": True,
        "formula_units": 0,
        "substrate_area_angstrom2": 236.37089524795562,
    },
    "C50": {
        "source": "C50/input_gamma.inp",
        "input_dir": "C50",
        "input_name": "input.inp",
        "project": "scnet_c50",
        "kpoint_mesh": "Gamma",
        "expected_electronic_outputs": True,
        "formula_units": 16,
        "substrate_area_angstrom2": 236.37089524795562,
    },
    "H1": {
        "source": "H1/input_gamma.inp",
        "input_dir": "H1",
        "input_name": "input.inp",
        "project": "scnet_h1",
        "kpoint_mesh": "Gamma",
        "expected_electronic_outputs": True,
        "formula_units": 32,
        "substrate_area_angstrom2": 236.37089524795562,
    },
    "H2": {
        "source": "H2/input_gamma.inp",
        "input_dir": "H2",
        "input_name": "input.inp",
        "project": "scnet_h2",
        "kpoint_mesh": "Gamma",
        "expected_electronic_outputs": True,
        "formula_units": 64,
        "substrate_area_angstrom2": 236.37089524795562,
    },
}

RESOURCES = {
    "00_check_environment": {"ntasks": 1, "hours": 1 / 6},
    "cu2te_bulk_gamma": {"ntasks": 4, "hours": 0.5},
    "cu2te_bulk_k222": {"ntasks": 4, "hours": 0.5},
    "cu2te_bulk_k333": {"ntasks": 4, "hours": 1.0},
    "cu2te_bulk_k444": {"ntasks": 4, "hours": 1.0},
    "B0": {"ntasks": 16, "hours": 6.0},
    "C50": {"ntasks": 16, "hours": 10.0},
    "H1": {"ntasks": 16, "hours": 12.0},
    "H2": {"ntasks": 24, "hours": 24.0},
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def write_lf(path: Path, text: str, encoding: str = "utf-8") -> None:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    path.write_bytes(normalized.encode(encoding))


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected exactly one {label}; found {count}")
    return text.replace(old, new, 1)


def transform_input(task_id: str, spec: dict) -> str:
    source = ROOT / "research_lite" / "inputs" / spec["source"]
    text = source.read_text(encoding="utf-8")
    text = re.sub(
        r"^# Generated by .*?$",
        "# Generated for SCNet East China 1 Kunshan; target CP2K 2024.1.",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    text = re.sub(
        r"^# PROFILE .*?$",
        "# Fixed-geometry research-lite prototype; not publication-converged.",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    text = re.sub(
        r"(?m)^\s*PROJECT\s+\S+\s*$",
        f"  PROJECT {spec['project']}",
        text,
        count=1,
    )
    text = text.replace(
        "CP2K 2024.3 PDOS/LDOS support",
        "the target CP2K 2024.1 PDOS/LDOS path",
    )

    if task_id.startswith("cu2te_bulk"):
        block_re = re.compile(r"\n\s*&KPOINTS\s*\n.*?&END KPOINTS\s*\n", re.S | re.I)
        match = block_re.search(text)
        if not match:
            raise RuntimeError("bulk source input does not contain one KPOINTS block")
        if task_id == "cu2te_bulk_gamma":
            text = block_re.sub(
                "\n    # Implicit Gamma: no explicit KPOINTS block.\n",
                text,
                count=1,
            )
        else:
            size = task_id[-3]
            replacement = (
                "\n    &KPOINTS\n"
                f"      SCHEME MONKHORST-PACK {size} {size} {size}\n"
                "    &END KPOINTS\n"
            )
            text = block_re.sub(replacement, text, count=1)
        upper = text.upper()
        for forbidden in ("&DOS", "&PDOS", "&LDOS", "V_HARTREE_CUBE", "E_DENSITY_CUBE"):
            if forbidden in upper:
                raise RuntimeError(f"energy-only bulk input contains {forbidden}")

    if task_id in {"H1", "H2"}:
        text = replace_once(text, "MAX_SCF 150", "MAX_SCF 250", "MAX_SCF")
        text = replace_once(text, "ADDED_MOS 40", "ADDED_MOS 100", "ADDED_MOS")
        text = replace_once(text, "ALPHA 0.15", "ALPHA 0.08", "MIXING ALPHA")
        text = replace_once(text, "NBROYDEN 8", "NBROYDEN 12", "NBROYDEN")
        text = replace_once(text, "NLUMO 40", "NLUMO 100", "PDOS NLUMO")

    if "EPS_SCF 1e-06" not in text:
        raise RuntimeError(f"{task_id}: EPS_SCF was changed unexpectedly")
    if "RUN_TYPE ENERGY" not in text:
        raise RuntimeError(f"{task_id}: only fixed-geometry ENERGY runs are allowed")
    return text.rstrip() + "\n"


def write_inputs() -> None:
    for task_id, spec in TASKS.items():
        destination_dir = PACKAGE / "inputs" / spec["input_dir"]
        destination_dir.mkdir(parents=True, exist_ok=True)
        destination = destination_dir / spec["input_name"]
        write_lf(destination, transform_input(task_id, spec))
        source_structure = SOURCE_INPUTS / spec["input_dir"] / "structure.extxyz"
        destination_structure = destination_dir / "structure.extxyz"
        write_lf(
            destination_structure,
            source_structure.read_text(encoding="utf-8"),
        )


def write_package_config() -> None:
    budget = sum(item["ntasks"] * item["hours"] for item in RESOURCES.values())
    task_records = {}
    for task_id, source_spec in TASKS.items():
        spec = dict(source_spec)
        input_dir = PACKAGE / "inputs" / spec["input_dir"]
        spec["input_sha256"] = sha256(input_dir / spec["input_name"])
        spec["structure_sha256"] = sha256(input_dir / "structure.extxyz")
        task_records[task_id] = spec
    payload = {
        "package": "server_scnet_2024_1",
        "target_platform": "SCNet East China 1 Kunshan",
        "partition": "kshctest02",
        "target_cp2k_version": "2024.1",
        "cp2k_executable": "/public/software/apps/cp2k/2024.1/exe/local/cp2k.popt",
        "cp2k_data_dir": "/public/software/apps/cp2k/2024.1/data",
        "node_cpu_cores": 32,
        "node_memory_mb_approx": 126500,
        "free_budget_cpu_hours": 2000,
        "maximum_requested_cpu_hours": budget,
        "server_calculations_actually_run": False,
        "tasks": task_records,
        "resources": RESOURCES,
        "strict_h1_parameters": {
            "added_mos": 100,
            "pdos_nlumo": 100,
            "mixing_alpha": 0.08,
            "nbroyden": 12,
            "max_scf": 250,
            "eps_scf": 1.0e-6,
            "electronic_temperature_K": 500,
            "method": "standard diagonalization",
        },
        "kpoint_convergence_threshold_ev_per_formula_unit": 0.01,
        "coverage_curvature_definition": "E(H1)+E(B0)-2*E(C50)",
        "scientific_boundary": (
            "No server calculation has been run. Old CP2K 2024.3 values are "
            "historical prototype evidence and are not paper-ready coverage energies."
        ),
    }
    write_lf(
        PACKAGE / "package_config.json",
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
    )


def validate_paths() -> None:
    bad = []
    for path in PACKAGE.rglob("*"):
        relative = path.relative_to(PACKAGE).as_posix()
        if any(ord(character) > 127 for character in relative) or " " in relative:
            bad.append(relative)
    if bad:
        raise RuntimeError(f"non-ASCII or space-containing server paths: {bad}")


def write_manifest() -> None:
    validate_paths()
    excluded_roots = {"runs", "results"}
    paths = []
    for path in PACKAGE.rglob("*"):
        if not path.is_file() or path.name == "upload_manifest.txt":
            continue
        relative = path.relative_to(PACKAGE)
        if relative.parts and relative.parts[0] in excluded_roots:
            continue
        if "__pycache__" in relative.parts or path.suffix.lower() == ".pyc":
            continue
        paths.append((relative.as_posix(), sha256(path)))
    lines = [f"{digest}  {relative}" for relative, digest in sorted(paths)]
    write_lf(
        PACKAGE / "upload_manifest.txt",
        "\n".join(lines) + "\n",
        encoding="ascii",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the SCNet CP2K 2024.1 package inputs")
    parser.add_argument(
        "--manifest-only",
        action="store_true",
        help="refresh upload_manifest.txt after authored package files are updated",
    )
    args = parser.parse_args()
    PACKAGE.mkdir(parents=True, exist_ok=True)
    if not args.manifest_only:
        write_inputs()
        write_package_config()
    write_manifest()
    print(PACKAGE)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
