from __future__ import annotations

import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ROOT, load_config, load_metadata, load_model

BASIS = {
    "Cu": ("TZVP-MOLOPT-SR-GTH-q11", "GTH-PBE-q11", 11),
    "Cd": ("TZVP-MOLOPT-SR-GTH-q12", "GTH-PBE-q12", 12),
    "Te": ("TZVP-MOLOPT-SR-GTH-q6", "GTH-PBE-q6", 6),
}


def fmt_vector(v) -> str:
    return " ".join(f"{float(x):16.9f}" for x in v)


def input_text(model_id: str, run_type: str, config: dict) -> str:
    atoms = load_model(model_id)
    meta = load_metadata(model_id)
    cp = config["cp2k"]
    project = f"{model_id}_{'sp' if run_type == 'ENERGY_FORCE' else 'test_opt'}"
    coord = "\n".join(f"      {s:2s} {p[0]:16.9f} {p[1]:16.9f} {p[2]:16.9f}" for s, p in zip(atoms.get_chemical_symbols(), atoms.positions))
    kinds = []
    for element in ("Cd", "Te", "Cu"):
        if element not in atoms.get_chemical_symbols():
            continue
        basis, potential, q = BASIS[element]
        kinds.append(f"""    &KIND {element}
      ELEMENT {element}
      BASIS_SET {basis}
      POTENTIAL {potential}
      # GTH valence-electron setting: q{q}
    &END KIND""")
    motion = ""
    if run_type == "GEO_OPT":
        fixed = " ".join(str(i) for i in meta["fixed_atom_indices_cp2k_1based"])
        motion = f"""
&MOTION
  &CONSTRAINT
    &FIXED_ATOMS
      LIST {fixed}
      COMPONENTS_TO_FIX XYZ
    &END FIXED_ATOMS
  &END CONSTRAINT
  &GEO_OPT
    OPTIMIZER BFGS
    MAX_ITER {cp['geo_opt_test_max_iter']}
    MAX_FORCE 4.5E-4
    RMS_FORCE 3.0E-4
    MAX_DR 3.0E-3
    RMS_DR 1.5E-3
  &END GEO_OPT
  &PRINT
    &TRAJECTORY
      FORMAT XYZ
    &END TRAJECTORY
    &FORCES ON
    &END FORCES
    &RESTART
      BACKUP_COPIES 1
    &END RESTART
  &END PRINT
&END MOTION
"""
    return f"""# Generated by scripts/generate_cp2k_inputs.py
# PROTOTYPE ONLY: slab size, k-points, basis and cutoff are not converged.
&GLOBAL
  PROJECT {project}
  RUN_TYPE {run_type}
  PRINT_LEVEL MEDIUM
&END GLOBAL

&FORCE_EVAL
  METHOD QUICKSTEP
  &DFT
    BASIS_SET_FILE_NAME {cp['basis_file']}
    POTENTIAL_FILE_NAME {cp['potential_file']}
    CHARGE 0
    MULTIPLICITY 1
    &QS
      EPS_DEFAULT 1.0E-12
    &END QS
    &POISSON
      PERIODIC XY
      PSOLVER ANALYTIC
    &END POISSON
    &MGRID
      CUTOFF {cp['cutoff_ry']}
      REL_CUTOFF {cp['rel_cutoff_ry']}
    &END MGRID
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF {cp['eps_scf']}
      MAX_SCF {cp['max_scf']}
      ADDED_MOS {cp['added_mos']}
      &DIAGONALIZATION
        ALGORITHM STANDARD
      &END DIAGONALIZATION
      &SMEAR ON
        METHOD FERMI_DIRAC
        ELECTRONIC_TEMPERATURE [K] {cp['electronic_temperature_k']}
      &END SMEAR
      &MIXING ON
        METHOD BROYDEN_MIXING
        ALPHA 0.20
        NBROYDEN 8
      &END MIXING
      &PRINT
        &RESTART ON
          BACKUP_COPIES 1
        &END RESTART
      &END PRINT
    &END SCF
    &XC
      &XC_FUNCTIONAL PBE
      &END XC_FUNCTIONAL
    &END XC
    &KPOINTS
      SCHEME GAMMA
    &END KPOINTS
  &END DFT
  &SUBSYS
    &CELL
      A {fmt_vector(atoms.cell[0])}
      B {fmt_vector(atoms.cell[1])}
      C {fmt_vector(atoms.cell[2])}
      PERIODIC XY
    &END CELL
    &COORD
{coord}
    &END COORD
{chr(10).join(kinds)}
  &END SUBSYS
  &PRINT
    &FORCES ON
    &END FORCES
  &END PRINT
&END FORCE_EVAL
{motion}"""


def write_scripts(model_dir: Path, model_id: str, config: dict):
    threads = config["cp2k"]["local_max_threads"]
    sh = f"""#!/usr/bin/env bash
set -euo pipefail
input=${{1:-single_point.inp}}
output=${{input%.inp}}.out
cmd=${{CP2K_CMD:-}}
if [[ -z "$cmd" ]]; then
  for candidate in cp2k.psmp cp2k.popt cp2k; do
    if command -v "$candidate" >/dev/null 2>&1; then cmd=$candidate; break; fi
  done
fi
if [[ -z "$cmd" ]]; then echo "ERROR: CP2K not found. Set CP2K_CMD." >&2; exit 127; fi
export OMP_NUM_THREADS=${{OMP_NUM_THREADS:-{threads}}}
"$cmd" -i "$input" -o "$output"
"${{PYTHON:-python}}" ../../scripts/parse_cp2k_output.py "$output" --input "$input"
"""
    ps1 = f"""param([string]$InputFile = 'single_point.inp')
$ErrorActionPreference = 'Stop'
$cmd = $env:CP2K_CMD
if (-not $cmd) {{ foreach ($candidate in @('cp2k.psmp','cp2k.popt','cp2k')) {{ if (Get-Command $candidate -ErrorAction SilentlyContinue) {{ $cmd=$candidate; break }} }} }}
if (-not $cmd) {{ throw 'CP2K not found. Set CP2K_CMD.' }}
if (-not $env:OMP_NUM_THREADS) {{ $env:OMP_NUM_THREADS='{threads}' }}
$OutputFile = [IO.Path]::ChangeExtension($InputFile, '.out')
& $cmd -i $InputFile -o $OutputFile
& $env:PYTHON ../../scripts/parse_cp2k_output.py $OutputFile --input $InputFile
"""
    cpus, wall = config["cp2k"]["slurm_cpus"], config["cp2k"]["slurm_time"]
    slurm = f"""#!/usr/bin/env bash
#SBATCH --job-name={model_id}_cute_proto
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --time={wall}
#SBATCH --output=slurm-%j.out
# Add site-specific account/partition/module or container settings before use.
set -euo pipefail
export OMP_NUM_THREADS=${{SLURM_CPUS_PER_TASK:-{cpus}}}
CP2K_CMD=${{CP2K_CMD:-cp2k.psmp}}
srun "$CP2K_CMD" -i single_point.inp -o single_point.out
"""
    for name, text in (("run_local.sh", sh), ("run_local.ps1", ps1), ("job.slurm", slurm)):
        path = model_dir / name
        path.write_text(text, encoding="utf-8", newline="\n")
        if name.endswith(".sh") or name.endswith(".slurm"):
            path.chmod(path.stat().st_mode | stat.S_IEXEC)


def main() -> int:
    config = load_config()
    for model_id in ("T0", "T1", "T2"):
        model_dir = ROOT / "models" / model_id
        (model_dir / "single_point.inp").write_text(input_text(model_id, "ENERGY_FORCE", config), encoding="utf-8", newline="\n")
        (model_dir / "test_geo_opt.inp").write_text(input_text(model_id, "GEO_OPT", config), encoding="utf-8", newline="\n")
        write_scripts(model_dir, model_id, config)
        print(f"generated CP2K inputs for {model_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
